# Generated by Django 2.2.4 on 2019-08-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0003_auto_20190823_1406'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='serial',
        ),
        migrations.AddField(
            model_name='project',
            name='serial',
            field=models.ManyToManyField(blank=True, null=True, to='serials.Serial'),
        ),
    ]
