# Generated by Django 2.2.2 on 2019-08-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190823_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['project_code']},
        ),
        migrations.AlterField(
            model_name='project',
            name='serial',
            field=models.ManyToManyField(blank=True, to='serials.Serial'),
        ),
    ]
