# Generated by Django 2.2.4 on 2019-08-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
