# Generated by Django 2.2.2 on 2019-08-24 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_auto_20190823_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['option_code']},
        ),
    ]
