# Generated by Django 2.2.4 on 2019-08-27 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0003_auto_20190823_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['option_code'], 'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
    ]
