# Generated by Django 2.2.4 on 2019-08-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20190823_2132'),
        ('stations', '0003_auto_20190823_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=50, unique=True, verbose_name='Part Number')),
                ('part_name', models.CharField(max_length=200, verbose_name='Part Description')),
                ('part_approved', models.BooleanField(default=False, verbose_name='Approved Type Design')),
                ('part_drawing', models.CharField(blank=True, max_length=100, verbose_name='Parent Document')),
                ('part_qty_per', models.DecimalField(decimal_places=2, default=1.0, max_digits=8, verbose_name='Shipset Qty')),
                ('part_replaces', models.CharField(blank=True, max_length=50, verbose_name='Replaces Part Number')),
                ('part_type', models.CharField(choices=[('P', 'Purchased'), ('M', 'Manufactured')], default='P', max_length=1, verbose_name='Type')),
                ('part_class', models.CharField(choices=[('ASY', 'Assembly'), ('CST', 'Customer Service'), ('FAB', 'Fabricated Part'), ('KBN', 'Kanban'), ('PUR', 'Purchased Part'), ('RAW', 'Raw Material'), ('TOO', 'Tooling'), ('VMI', 'Vendor Managed Inventory')], default='PUR', max_length=3, verbose_name='Class')),
                ('part_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='Cost')),
                ('part_ium', models.CharField(default='EA', max_length=2, verbose_name='IUM')),
                ('part_pum', models.CharField(default='EA', max_length=2, verbose_name='PUM')),
                ('part_factor', models.IntegerField(default=1, verbose_name='Conversion Factor')),
                ('part_min_order', models.IntegerField(default=0, verbose_name='Min Order Quantity')),
                ('part_lead_time', models.IntegerField(default=0, verbose_name='Lead Time')),
                ('part_rubber', models.BooleanField(default=False, verbose_name='Rubber Like Material')),
                ('part_temp_control', models.BooleanField(default=False, verbose_name='Temperature Controlled')),
                ('part_shelf_life', models.BooleanField(default=False, verbose_name='Shelf Life')),
                ('part_min_stock', models.IntegerField(default=0, verbose_name='Min On Hand Quantity')),
                ('part_lot_size', models.IntegerField(default=0, verbose_name='Lot Size')),
                ('part_pln_code', models.CharField(blank=True, max_length=2, verbose_name='Planning Code')),
                ('part_serial_track', models.BooleanField(default=False, verbose_name='Serial Tracked')),
                ('part_lot_track', models.BooleanField(default=False, verbose_name='Lot Tracked')),
                ('part_non_stock', models.BooleanField(default=False, verbose_name='Non-Stock')),
                ('part_qty_bearing', models.BooleanField(default=True, verbose_name='Quantity Bearing')),
                ('part_qasr', models.CharField(max_length=200, verbose_name='Quality Requirements')),
                ('part_trace_id', models.BooleanField(default=True, verbose_name='Trace ID Required')),
                ('products', models.ManyToManyField(blank=True, to='products.Product', verbose_name='Products')),
                ('stations', models.ManyToManyField(blank=True, to='stations.Station', verbose_name='Stations')),
            ],
            options={
                'ordering': ['part_number'],
            },
        ),
    ]
