# Generated by Django 2.2.4 on 2019-08-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_qasr',
            field=models.CharField(blank=True, max_length=200, verbose_name='Quality Requirements'),
        ),
    ]
