# Generated by Django 2.2.4 on 2019-08-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_auto_20190827_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_factor',
            field=models.PositiveIntegerField(default=1, verbose_name='Conversion Factor'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_lead_time',
            field=models.PositiveIntegerField(default=0, verbose_name='Lead Time'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_lot_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Lot Size'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_min_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Min Order Quantity'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_min_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Min On Hand Quantity'),
        ),
    ]
