# Generated by Django 2.2.4 on 2019-08-27 23:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_auto_20190827_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'get_latest_by': ['-part_created'], 'ordering': ['part_number'], 'verbose_name': 'Part', 'verbose_name_plural': 'Parts'},
        ),
        migrations.AddField(
            model_name='part',
            name='part_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Created'),
            preserve_default=False,
        ),
    ]
