# Generated by Django 2.2.4 on 2019-08-27 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('comment_text', models.TextField(blank=True, verbose_name='Comment Text')),
                ('comment_created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_creators', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parent_comment', models.ManyToManyField(blank=True, related_name='_comment_parent_comment_+', to='comments.Comment', verbose_name='Parent Comment')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-comment_created'],
                'get_latest_by': ['-comment_created'],
            },
        ),
    ]
