# Generated by Django 2.2.4 on 2019-08-27 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revisions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='options.Option', verbose_name='Option'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='rev_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='rev_ed_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='ED Code'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='serial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serials.Serial', verbose_name='Serial Effectivity'),
        ),
    ]
