# Generated by Django 2.2.4 on 2019-08-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisions', '0002_auto_20190827_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='rev_effective',
            field=models.DateField(blank=True, null=True, verbose_name='Effective Date'),
        ),
    ]
