# Generated by Django 2.2.4 on 2019-08-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisions', '0003_auto_20190827_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revision',
            options={'get_latest_by': ['rev_created'], 'ordering': ['part__part_number', '-rev_effective', '-rev_number'], 'verbose_name': 'Revision', 'verbose_name_plural': 'Revisions'},
        ),
        migrations.AddField(
            model_name='revision',
            name='rev_control_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Control Number'),
        ),
    ]
