# Generated by Django 2.2.4 on 2019-08-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
