# Generated by Django 2.2.2 on 2019-08-24 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_auto_20190823_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['station_code']},
        ),
    ]
