# Generated by Django 2.2.4 on 2019-08-27 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_auto_20190823_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['station_code'], 'verbose_name': 'Station', 'verbose_name_plural': 'Stations'},
        ),
    ]
