# Generated by Django 2.2.4 on 2019-08-27 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=12, verbose_name='Task Name')),
                ('task_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('task_notes', models.TextField(blank=True, verbose_name='Task Notes')),
                ('task_due', models.DateField(blank=True, null=True, verbose_name='Date Created')),
                ('task_completed', models.DateField(blank=True, null=True, verbose_name='Date Completed')),
                ('task_assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('task_created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_creators', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-task_created'],
                'get_latest_by': ['task_created'],
            },
        ),
    ]
