# Generated by Django 2.2.4 on 2019-08-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_comments',
            field=models.ManyToManyField(blank=True, to='comments.Comment', verbose_name='Comments'),
        ),
    ]
