# Generated by Django 2.2.4 on 2019-08-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='serial_number',
            field=models.CharField(max_length=4),
        ),
    ]
