# Generated by Django 2.2.4 on 2019-08-23 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0002_auto_20190823_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='aircraft',
            field=models.CharField(choices=[('100', 'Kodiak 100'), ('200', 'Kodiak 200')], default='100', max_length=3),
        ),
        migrations.AlterField(
            model_name='serial',
            name='serial_number',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.Station'),
        ),
    ]
