# Generated by Django 2.2.2 on 2019-08-24 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0005_auto_20190823_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.Station'),
        ),
    ]
