# Generated by Django 2.2.4 on 2019-08-27 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0006_auto_20190823_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serial',
            options={'ordering': ['product', 'serial_number', 'station']},
        ),
    ]
