# Generated by Django 2.2.4 on 2019-08-27 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0007_auto_20190827_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serial',
            options={'ordering': ['product', 'serial_number', 'station'], 'verbose_name': 'Serial', 'verbose_name_plural': 'Serials'},
        ),
    ]
