# Generated by Django 2.2.2 on 2019-08-27 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_auto_20190823_2137'),
        ('parts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Psw',
            fields=[
                ('part_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parts.Part')),
                ('psw_number', models.PositiveIntegerField(editable=False, unique=True, verbose_name='PSW Number')),
                ('psw_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('psw_requestor', models.EmailField(max_length=100, verbose_name='Submitter Email')),
                ('psw_need_qty', models.PositiveIntegerField(blank=True, default=0, verbose_name='Quantity Required')),
                ('psw_due_date', models.DateField(blank=True, verbose_name='Date Needed')),
                ('psw_part_rev', models.CharField(blank=True, max_length=50, verbose_name='Revision')),
                ('psw_notes', models.TextField(blank=True, verbose_name='PSW Notes')),
                ('psw_req_min', models.IntegerField(default=0, verbose_name='Requested Min Stock')),
                ('supplier_name', models.CharField(blank=True, max_length=100, verbose_name='Supplier Name')),
                ('supplier_id', models.CharField(blank=True, max_length=8, verbose_name='Supplier ID')),
                ('purchase_point', models.CharField(blank=True, max_length=4, verbose_name='Purchase Point')),
                ('supplier_approved', models.BooleanField(default=True, verbose_name='Approved Supplier')),
                ('supplier_part_number', models.CharField(blank=True, max_length=50, verbose_name='Supplier Part Number')),
                ('po_number', models.CharField(blank=True, max_length=10, verbose_name='PO Number')),
                ('po_due_date', models.DateField(blank=True, verbose_name='PO Due Date')),
                ('purchasing_date', models.DateField(blank=True, verbose_name='Purchasing Complete')),
                ('scm_date', models.DateField(blank=True, verbose_name='Supply Chain Complete')),
                ('quality_date', models.DateField(blank=True, verbose_name='Quality Complete')),
                ('cit_date', models.DateField(blank=True, verbose_name='CIT Complete')),
                ('accounting_date', models.DateField(blank=True, verbose_name='Accounting Complete')),
                ('purchase_date', models.DateField(blank=True, verbose_name='Purchase Date')),
                ('psw_status', models.CharField(choices=[('NEW', 'New'), ('PEN', 'Pending Assignment'), ('PUR', 'Purchasing'), ('SCM', 'Supply Chain'), ('QUA', 'Quality'), ('CIT', 'CIT'), ('ACC', 'Accounting'), ('BUY', 'Pending Purchase'), ('CMP', 'Complete'), ('HLD', 'On Hold'), ('CAN', 'Cancelled')], default='NEW', max_length=3, verbose_name='PSW Status')),
                ('psw_completed', models.DateField(blank=True, verbose_name='Completed Date')),
                ('accounting_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_users', to=settings.AUTH_USER_MODEL, verbose_name='Accounting User')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('cit_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cit_users', to=settings.AUTH_USER_MODEL, verbose_name='CIT User')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project')),
                ('purchasing_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchasing_users', to=settings.AUTH_USER_MODEL, verbose_name='Purchasing User')),
                ('quality_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_users', to=settings.AUTH_USER_MODEL, verbose_name='Quality User')),
                ('scm_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scm_users', to=settings.AUTH_USER_MODEL, verbose_name='Supply Chain User')),
            ],
            options={
                'ordering': ['psw_number'],
            },
            bases=('parts.part',),
        ),
    ]
