# Generated by Django 2.2.4 on 2019-08-27 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psw', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psw',
            options={'get_latest_by': ['psw_number', 'psw_created'], 'ordering': ['-psw_number'], 'verbose_name': 'PSW', 'verbose_name_plural': "PSW's"},
        ),
        migrations.AlterField(
            model_name='psw',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='psw',
            name='psw_req_min',
            field=models.PositiveIntegerField(default=0, verbose_name='Requested Min Stock'),
        ),
    ]
