# Generated by Django 2.2.4 on 2019-08-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('psw', '0002_auto_20190827_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='psw',
            name='psw_comments',
            field=models.ManyToManyField(blank=True, to='comments.Comment', verbose_name='Comments'),
        ),
    ]
